export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAIL = "CREATE_CHAT_FAIL";

export const FETCH_CHAT_REQUEST = "FETCH_CHAT_REQUEST";
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";
export const FETCH_CHAT_FAIL = "FETCH_CHAT_FAIL";

export const SELECT_CHAT_REQUEST = "SELECT_CHAT_REQUEST";
export const SELECT_CHAT_SUCCESS = "SELECT_CHAT_SUCCESS";
export const SELECT_CHAT_FAIL = "SELECT_CHAT_FAIL";
export const SELECT_CHAT_RESET = "SELECT_CHAT_RESET";
